TRUNCATE TABLE llx_c_cfdixml_usocfdi;
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('G02','Devoluciones, descuentos o bonificaciones.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('G03','Gastos en general.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I01','Construcciones.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('G01','Adquisición de mercancías',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I02','Mobiliario y equipo de oficina por inversiones.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I03','Equipo de transporte.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I04','Equipo de computo y accesorios.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I05','Dados, troqueles, moldes, matrices y herramental.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I06','Comunicaciones telefónicas.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I07','Comunicaciones satelitales.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('I08','Otra maquinaria y equipo.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D01','Honorarios médicos, dentales y gastos hospitalarios.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D02','Gastos médicos por incapacidad o discapacidad.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D03','Gastos funerales.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D04','Donativos.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D05','Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D06','Aportaciones voluntarias al SAR.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D07','Primas por seguros de gastos médicos.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D08','Gastos de transportación escolar obligatoria.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D09','Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('D10','Pagos por servicios educativos (colegiaturas).',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('S01','Sin efectos fiscales.  ',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('CP01','Pagos',1);
INSERT INTO llx_c_cfdixml_usocfdi (code,label,active) VALUES ('CN01','Nómina',1);
